spring:
  config:
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: ${DATABASE.ENDPOINT_URL}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver