spring:
  config:
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update
      #      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    url: ${DATABASE.ENDPOINT_URL}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      springframework:
        security: DEBUG
# Swagger 설정
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
